version: '3.1'

services:
  find-course-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db
    # volumes:
    #   - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: find-course-db
    depends_on:
      - find-course-db